import { downloadZip } from "client-zip";
import { ImageConfig } from "../../app/game/Config";
import { GameConfig } from "./GameConfigForm";

declare const VERSION: string;

export class Downloader {
  public async downloadAsZip(
    imageConfig: ImageConfig[],
    gameConfig: GameConfig
  ) {
    const app = await fetch("../app/app.js");
    const index = {
      name: "index.html",
      lastModified: new Date(),
      input: this.createTemplate(imageConfig, gameConfig),
    };
    const blob = await downloadZip([index, app]).blob();
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "StripBreakout.zip";
    link.click();
    link.remove();
  }

  private createTemplate(
    imageConfig: ImageConfig[],
    gameConfig: GameConfig
  ) {
    const stageConfigString = imageConfig.map((config) => {
      return `
                {
                    image: ${JSON.stringify(config)},
                    block: {
                        splitX: isMobileOs ? ${gameConfig.spSplit} : ${
          gameConfig.pcSplit
      },
                        splitY: isMobileOs ? ${gameConfig.spSplit} : ${
          gameConfig.pcSplit
      }
                    },
                    clear: {
                      achievement: ${gameConfig.achievement},
                    },
                    player: {
                        life: ${gameConfig.life}
                    }
                }
            `;
    });

    return `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Z2StripBreakout</title>
  </head>
  <body>
    <div style="display: flex; flex-direction: column; align-items: center; justify-content: center">
        <div id="stbo-app"></div>
        <div style="font-size: 12px">Generated by Z2StripBreakout version ${VERSION}</div>
    </div>
    <script type="text/javascript" src="./app.js"></script>
    <script type="text/javascript">
      StripBreakout(document.getElementById("stbo-app"), (isMobileOs) => {
          return { 
              stages: [${stageConfigString.join(",")}]
          }
      });
    </script>
  </body>
</html>
`;
  }
}
